language: go
go:
  - 1.11.x
  - 1.12.x
  - tip
env:
  - GO111MODULE=on
install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - golangci-lint run --fast ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
